import { Router } from 'express';
import authRoutes from '../modules/auth/auth.route.js';
import departmentRoutes from '../modules/department/department.route.js';
import employeeRoutes from '../modules/employee/employee.route.js';
import manufacturerRoutes from '../modules/manufacturer/manufacturer.route.js';
import vehicleMasterRoutes from '../modules/vehicleMaster/vehicleMaster.route.js';
import partsMasterRoutes from '../modules/partsMaster/partsMaster.route.js';
import dealerRoutes from '../modules/dealer/dealer.route.js';
import idGeneratorRoutes from '../modules/idGenerator/idGenerator.route.js';
import frameNumberRoutes from '../modules/frameNumber/frameNumber.route.js';
import branchRoutes from '../modules/branch/branch.route.js';
import companyRoutes from '../modules/company/company.route.js';
import roleAccessRoutes from '../modules/roleAccess/roleAccess.route.js';
import locationRoutes from '../modules/location/location.route.js';
import vehicleStockInwardRoutes from '../modules/vehicleStockInward/vehicleStockInward.route.js';
const router = Router();
router.use('/auth', authRoutes);
router.use('/department', departmentRoutes);
router.use('/employee', employeeRoutes);
router.use('/user', employeeRoutes);
router.use('/manufacturer', manufacturerRoutes);
router.use('/vehicle-master', vehicleMasterRoutes);
router.use('/parts-master', partsMasterRoutes);
router.use('/dealer', dealerRoutes);
router.use('/id-generator', idGeneratorRoutes);
router.use('/frame-number', frameNumberRoutes);
router.use('/branches', branchRoutes);
router.use('/company', companyRoutes);
router.use('/role-access', roleAccessRoutes);
router.use('/location', locationRoutes);
router.use('/vehicle-stock-inward', vehicleStockInwardRoutes);
export default router;
//# sourceMappingURL=index.js.map