export declare class PartsMasterService {
    static getAll(): Promise<({
        hsn: {
            id: string;
            createdById: string | null;
            createdAt: Date;
            updatedAt: Date;
            code: string | null;
            igst: number | null;
            cgst: number | null;
            sgst: number | null;
            cess: number | null;
            description: string | null;
        } | null;
        manufacturer: {
            id: string;
            createdById: string | null;
            createdAt: Date;
            updatedAt: Date;
            name: string | null;
            code: string | null;
            email: string | null;
            addressId: string | null;
            gst: string | null;
            logo: string | null;
            vehicleManufacturer: boolean | null;
        } | null;
        vehicleSuit: {
            id: string;
            createdById: string | null;
            createdAt: Date;
            updatedAt: Date;
            vehicleId: string | null;
            partsMasterId: string | null;
        }[];
    } & {
        id: string;
        createdById: string | null;
        createdAt: Date;
        updatedAt: Date;
        manufacturerId: string | null;
        category: string | null;
        hsnId: string | null;
        color: string | null;
        url: string[];
        partNumber: string;
        partName: string | null;
        displayName: string | null;
        oldPartNum: string | null;
        largeCategoryName: string | null;
        showInConsumer: boolean | null;
        showInAutoCloud: boolean | null;
        moq: number | null;
        mrp: number | null;
        ndp: number | null;
        wefDate: Date | null;
        partStatus: string | null;
        remarks: string | null;
        size: string | null;
        mainPartNumber: string | null;
    })[]>;
    static getById(id: string): Promise<({
        hsn: {
            id: string;
            createdById: string | null;
            createdAt: Date;
            updatedAt: Date;
            code: string | null;
            igst: number | null;
            cgst: number | null;
            sgst: number | null;
            cess: number | null;
            description: string | null;
        } | null;
        manufacturer: {
            id: string;
            createdById: string | null;
            createdAt: Date;
            updatedAt: Date;
            name: string | null;
            code: string | null;
            email: string | null;
            addressId: string | null;
            gst: string | null;
            logo: string | null;
            vehicleManufacturer: boolean | null;
        } | null;
        vehicleSuit: {
            id: string;
            createdById: string | null;
            createdAt: Date;
            updatedAt: Date;
            vehicleId: string | null;
            partsMasterId: string | null;
        }[];
    } & {
        id: string;
        createdById: string | null;
        createdAt: Date;
        updatedAt: Date;
        manufacturerId: string | null;
        category: string | null;
        hsnId: string | null;
        color: string | null;
        url: string[];
        partNumber: string;
        partName: string | null;
        displayName: string | null;
        oldPartNum: string | null;
        largeCategoryName: string | null;
        showInConsumer: boolean | null;
        showInAutoCloud: boolean | null;
        moq: number | null;
        mrp: number | null;
        ndp: number | null;
        wefDate: Date | null;
        partStatus: string | null;
        remarks: string | null;
        size: string | null;
        mainPartNumber: string | null;
    }) | null>;
    static create(data: any): Promise<{
        hsn: {
            id: string;
            createdById: string | null;
            createdAt: Date;
            updatedAt: Date;
            code: string | null;
            igst: number | null;
            cgst: number | null;
            sgst: number | null;
            cess: number | null;
            description: string | null;
        } | null;
        manufacturer: {
            id: string;
            createdById: string | null;
            createdAt: Date;
            updatedAt: Date;
            name: string | null;
            code: string | null;
            email: string | null;
            addressId: string | null;
            gst: string | null;
            logo: string | null;
            vehicleManufacturer: boolean | null;
        } | null;
        vehicleSuit: {
            id: string;
            createdById: string | null;
            createdAt: Date;
            updatedAt: Date;
            vehicleId: string | null;
            partsMasterId: string | null;
        }[];
    } & {
        id: string;
        createdById: string | null;
        createdAt: Date;
        updatedAt: Date;
        manufacturerId: string | null;
        category: string | null;
        hsnId: string | null;
        color: string | null;
        url: string[];
        partNumber: string;
        partName: string | null;
        displayName: string | null;
        oldPartNum: string | null;
        largeCategoryName: string | null;
        showInConsumer: boolean | null;
        showInAutoCloud: boolean | null;
        moq: number | null;
        mrp: number | null;
        ndp: number | null;
        wefDate: Date | null;
        partStatus: string | null;
        remarks: string | null;
        size: string | null;
        mainPartNumber: string | null;
    }>;
    static update(id: string, data: any): Promise<({
        hsn: {
            id: string;
            createdById: string | null;
            createdAt: Date;
            updatedAt: Date;
            code: string | null;
            igst: number | null;
            cgst: number | null;
            sgst: number | null;
            cess: number | null;
            description: string | null;
        } | null;
        manufacturer: {
            id: string;
            createdById: string | null;
            createdAt: Date;
            updatedAt: Date;
            name: string | null;
            code: string | null;
            email: string | null;
            addressId: string | null;
            gst: string | null;
            logo: string | null;
            vehicleManufacturer: boolean | null;
        } | null;
        vehicleSuit: {
            id: string;
            createdById: string | null;
            createdAt: Date;
            updatedAt: Date;
            vehicleId: string | null;
            partsMasterId: string | null;
        }[];
    } & {
        id: string;
        createdById: string | null;
        createdAt: Date;
        updatedAt: Date;
        manufacturerId: string | null;
        category: string | null;
        hsnId: string | null;
        color: string | null;
        url: string[];
        partNumber: string;
        partName: string | null;
        displayName: string | null;
        oldPartNum: string | null;
        largeCategoryName: string | null;
        showInConsumer: boolean | null;
        showInAutoCloud: boolean | null;
        moq: number | null;
        mrp: number | null;
        ndp: number | null;
        wefDate: Date | null;
        partStatus: string | null;
        remarks: string | null;
        size: string | null;
        mainPartNumber: string | null;
    }) | null>;
    static delete(id: string): Promise<{
        id: string;
        createdById: string | null;
        createdAt: Date;
        updatedAt: Date;
        manufacturerId: string | null;
        category: string | null;
        hsnId: string | null;
        color: string | null;
        url: string[];
        partNumber: string;
        partName: string | null;
        displayName: string | null;
        oldPartNum: string | null;
        largeCategoryName: string | null;
        showInConsumer: boolean | null;
        showInAutoCloud: boolean | null;
        moq: number | null;
        mrp: number | null;
        ndp: number | null;
        wefDate: Date | null;
        partStatus: string | null;
        remarks: string | null;
        size: string | null;
        mainPartNumber: string | null;
    }>;
}
//# sourceMappingURL=partsMaster.service.d.ts.map